import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import './globals.css'

import { ThemeProvider } from '@/components/theme-provider'
import { Navbar } from '@/components/layout/navbar'
import { Sidebar } from '@/components/layout/sidebar'
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from '@/components/ui/resizable'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'examor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, 'min-h-screen')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem>
          <ResizablePanelGroup
            autoSaveId="examor-layout"
            direction="horizontal"
            className="max-h-screen">
            <ResizablePanel defaultSize={10} minSize={7} maxSize={15}>
              <Sidebar />
            </ResizablePanel>

            <ResizableHandle withHandle />

            <ResizablePanel className="flex flex-col">
              <Navbar />
              <main className="w-full p-6 flex-1 overflow-y-scroll">
                {children}
              </main>
            </ResizablePanel>
          </ResizablePanelGroup>
        </ThemeProvider>
      </body>
    </html>
  )
}
