/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Answer: typeof import('./src/components/Answer.vue')['default']
    AzureIcon: typeof import('./src/components/icons/AzureIcon.vue')['default']
    EmptyBlock: typeof import('./src/components/EmptyBlock.vue')['default']
    FilesTable: typeof import('./src/components/FilesTable.vue')['default']
    NoteHeader: typeof import('./src/components/NoteHeader.vue')['default']
    NotionIcon: typeof import('./src/components/icons/NotionIcon.vue')['default']
    OpenaiIcon: typeof import('./src/components/icons/OpenaiIcon.vue')['default']
    PineconeIcon: typeof import('./src/components/icons/PineconeIcon.vue')['default']
    QuestionTable: typeof import('./src/components/QuestionTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TUpload: typeof import('tdesign-vue-next')['Upload']
    UploadFileDialog: typeof import('./src/components/UploadFileDialog.vue')['default']
    UploadingFiles: typeof import('./src/components/UploadingFiles.vue')['default']
  }
}
