/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Answer: typeof import('./src/components/Answer.vue')['default']
    AzureIcon: typeof import('./src/components/icons/AzureIcon.vue')['default']
    NotionIcon: typeof import('./src/components/icons/NotionIcon.vue')['default']
    OpenaiIcon: typeof import('./src/components/icons/OpenaiIcon.vue')['default']
    PineconeIcon: typeof import('./src/components/icons/PineconeIcon.vue')['default']
    QuestionTable: typeof import('./src/components/QuestionTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TTable: typeof import('tdesign-vue-next')['Table']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
