/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AzureIcon: typeof import('./src/components/icons/AzureIcon.vue')['default']
    EmptyBlock: typeof import('./src/components/blocks/EmptyBlock.vue')['default']
    ExamineBlock: typeof import('./src/components/blocks/ExamineBlock.vue')['default']
    ExportDialog: typeof import('./src/components/dialogs/ExportDialog.vue')['default']
    FilesTable: typeof import('./src/components/tables/FilesTable.vue')['default']
    ImportDialog: typeof import('./src/components/dialogs/ImportDialog.vue')['default']
    ImportQuestionBankDialog: typeof import('./src/components/dialogs/ImportQuestionBankDialog.vue')['default']
    NoteHeader: typeof import('./src/components/headers/NoteHeader.vue')['default']
    NotionIcon: typeof import('./src/components/icons/NotionIcon.vue')['default']
    OpenaiIcon: typeof import('./src/components/icons/OpenaiIcon.vue')['default']
    PineconeIcon: typeof import('./src/components/icons/PineconeIcon.vue')['default']
    QuestionBankCard: typeof import('./src/components/card/QuestionBankCard.vue')['default']
    QuestionBlock: typeof import('./src/components/blocks/QuestionBlock.vue')['default']
    QuestionTable: typeof import('./src/components/tables/QuestionTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/globals/SnackBar.vue')['default']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TUpload: typeof import('tdesign-vue-next')['Upload']
    UploadFileDialog: typeof import('./src/components/dialogs/UploadFileDialog.vue')['default']
    UploadForm: typeof import('./src/components/forms/UploadForm.vue')['default']
    UploadingFloatFrame: typeof import('./src/components/globals/UploadingFloatFrame.vue')['default']
  }
}
